import {
  AchievementType,
  MissionType,
  VocabularyLevel,
} from "../../src/generated/prisma/enums";

export type VocabularySeed = {
  word: string;
  pronunciation: string;
  translation: string;
  example: string;
  exampleTranslation: string;
  category: string;
  level: (typeof VocabularyLevel)[keyof typeof VocabularyLevel];
};

const vocabulary = (
  word: string,
  pronunciation: string,
  translation: string,
  example: string,
  exampleTranslation: string,
  category: string,
  level: VocabularySeed["level"],
): VocabularySeed => ({
  word,
  pronunciation,
  translation,
  example,
  exampleTranslation,
  category,
  level,
});

export const vocabularySeed: readonly VocabularySeed[] = [
  vocabulary(
    "hello",
    "/həˈloʊ/",
    "olá",
    "Hello, it is nice to meet you.",
    "Olá, é um prazer conhecer você.",
    "Saudações",
    VocabularyLevel.BEGINNER,
  ),
  vocabulary(
    "goodbye",
    "/ˌɡʊdˈbaɪ/",
    "tchau",
    "She waved goodbye before leaving.",
    "Ela acenou tchau antes de sair.",
    "Saudações",
    VocabularyLevel.BEGINNER,
  ),
  vocabulary(
    "please",
    "/pliːz/",
    "por favor",
    "Please open the window.",
    "Por favor, abra a janela.",
    "Comunicação",
    VocabularyLevel.BEGINNER,
  ),
  vocabulary(
    "thanks",
    "/θæŋks/",
    "obrigado",
    "Thanks for your help today.",
    "Obrigado pela sua ajuda hoje.",
    "Comunicação",
    VocabularyLevel.BEGINNER,
  ),
  vocabulary(
    "family",
    "/ˈfæməli/",
    "família",
    "My family lives near the beach.",
    "Minha família mora perto da praia.",
    "Pessoas",
    VocabularyLevel.BEGINNER,
  ),
  vocabulary(
    "friend",
    "/frend/",
    "amigo",
    "Leo is my best friend.",
    "Leo é meu melhor amigo.",
    "Pessoas",
    VocabularyLevel.BEGINNER,
  ),
  vocabulary(
    "house",
    "/haʊs/",
    "casa",
    "Their house has a blue door.",
    "A casa deles tem uma porta azul.",
    "Casa",
    VocabularyLevel.BEGINNER,
  ),
  vocabulary(
    "kitchen",
    "/ˈkɪtʃɪn/",
    "cozinha",
    "Breakfast is ready in the kitchen.",
    "O café da manhã está pronto na cozinha.",
    "Casa",
    VocabularyLevel.BEGINNER,
  ),
  vocabulary(
    "water",
    "/ˈwɔːtər/",
    "água",
    "Could I have a glass of water?",
    "Eu poderia tomar um copo de água?",
    "Alimentação",
    VocabularyLevel.BEGINNER,
  ),
  vocabulary(
    "bread",
    "/bred/",
    "pão",
    "We bought fresh bread this morning.",
    "Nós compramos pão fresco esta manhã.",
    "Alimentação",
    VocabularyLevel.BEGINNER,
  ),
  vocabulary(
    "school",
    "/skuːl/",
    "escola",
    "The children walk to school.",
    "As crianças vão a pé para a escola.",
    "Educação",
    VocabularyLevel.BEGINNER,
  ),
  vocabulary(
    "teacher",
    "/ˈtiːtʃər/",
    "professor",
    "Our teacher explains everything clearly.",
    "Nosso professor explica tudo com clareza.",
    "Educação",
    VocabularyLevel.BEGINNER,
  ),
  vocabulary(
    "work",
    "/wɜːrk/",
    "trabalho",
    "I start work at nine.",
    "Eu começo o trabalho às nove.",
    "Trabalho",
    VocabularyLevel.BEGINNER,
  ),
  vocabulary(
    "money",
    "/ˈmʌni/",
    "dinheiro",
    "He is saving money for a trip.",
    "Ele está economizando dinheiro para uma viagem.",
    "Cotidiano",
    VocabularyLevel.BEGINNER,
  ),
  vocabulary(
    "today",
    "/təˈdeɪ/",
    "hoje",
    "The museum is closed today.",
    "O museu está fechado hoje.",
    "Tempo",
    VocabularyLevel.BEGINNER,
  ),
  vocabulary(
    "tomorrow",
    "/təˈmɒroʊ/",
    "amanhã",
    "We will talk again tomorrow.",
    "Nós conversaremos novamente amanhã.",
    "Tempo",
    VocabularyLevel.BEGINNER,
  ),
  vocabulary(
    "happy",
    "/ˈhæpi/",
    "feliz",
    "The good news made everyone happy.",
    "A boa notícia deixou todos felizes.",
    "Emoções",
    VocabularyLevel.BEGINNER,
  ),
  vocabulary(
    "tired",
    "/ˈtaɪərd/",
    "cansado",
    "I feel tired after the long walk.",
    "Eu me sinto cansado depois da longa caminhada.",
    "Emoções",
    VocabularyLevel.BEGINNER,
  ),

  vocabulary(
    "appointment",
    "/əˈpɔɪntmənt/",
    "compromisso",
    "I have a dentist appointment at noon.",
    "Tenho uma consulta com o dentista ao meio-dia.",
    "Cotidiano",
    VocabularyLevel.INTERMEDIATE,
  ),
  vocabulary(
    "neighborhood",
    "/ˈneɪbərhʊd/",
    "vizinhança",
    "This neighborhood is quiet at night.",
    "Esta vizinhança é tranquila à noite.",
    "Casa",
    VocabularyLevel.INTERMEDIATE,
  ),
  vocabulary(
    "commute",
    "/kəˈmjuːt/",
    "deslocamento diário",
    "Her commute takes about forty minutes.",
    "O deslocamento diário dela leva cerca de quarenta minutos.",
    "Viagem",
    VocabularyLevel.INTERMEDIATE,
  ),
  vocabulary(
    "luggage",
    "/ˈlʌɡɪdʒ/",
    "bagagem",
    "Your luggage is already on the train.",
    "Sua bagagem já está no trem.",
    "Viagem",
    VocabularyLevel.INTERMEDIATE,
  ),
  vocabulary(
    "destination",
    "/ˌdestɪˈneɪʃən/",
    "destino",
    "Lisbon is our final destination.",
    "Lisboa é nosso destino final.",
    "Viagem",
    VocabularyLevel.INTERMEDIATE,
  ),
  vocabulary(
    "recipe",
    "/ˈresəpi/",
    "receita",
    "This recipe uses seasonal vegetables.",
    "Esta receita usa legumes da estação.",
    "Alimentação",
    VocabularyLevel.INTERMEDIATE,
  ),
  vocabulary(
    "flavor",
    "/ˈfleɪvər/",
    "sabor",
    "The herbs add flavor to the soup.",
    "As ervas acrescentam sabor à sopa.",
    "Alimentação",
    VocabularyLevel.INTERMEDIATE,
  ),
  vocabulary(
    "deadline",
    "/ˈdedlaɪn/",
    "prazo final",
    "The project deadline is next Friday.",
    "O prazo final do projeto é na próxima sexta-feira.",
    "Trabalho",
    VocabularyLevel.INTERMEDIATE,
  ),
  vocabulary(
    "colleague",
    "/ˈkɒliːɡ/",
    "colega",
    "A colleague reviewed my presentation.",
    "Um colega revisou minha apresentação.",
    "Trabalho",
    VocabularyLevel.INTERMEDIATE,
  ),
  vocabulary(
    "improve",
    "/ɪmˈpruːv/",
    "melhorar",
    "Daily practice will improve your pronunciation.",
    "A prática diária melhorará sua pronúncia.",
    "Educação",
    VocabularyLevel.INTERMEDIATE,
  ),
  vocabulary(
    "knowledge",
    "/ˈnɒlɪdʒ/",
    "conhecimento",
    "Travel can broaden our knowledge of history.",
    "Viajar pode ampliar nosso conhecimento de história.",
    "Educação",
    VocabularyLevel.INTERMEDIATE,
  ),
  vocabulary(
    "decision",
    "/dɪˈsɪʒən/",
    "decisão",
    "It was a difficult decision to make.",
    "Foi uma decisão difícil de tomar.",
    "Comunicação",
    VocabularyLevel.INTERMEDIATE,
  ),
  vocabulary(
    "suggest",
    "/səˈdʒest/",
    "sugerir",
    "Could you suggest a good restaurant?",
    "Você poderia sugerir um bom restaurante?",
    "Comunicação",
    VocabularyLevel.INTERMEDIATE,
  ),
  vocabulary(
    "confident",
    "/ˈkɒnfɪdənt/",
    "confiante",
    "She felt confident before the interview.",
    "Ela se sentiu confiante antes da entrevista.",
    "Emoções",
    VocabularyLevel.INTERMEDIATE,
  ),
  vocabulary(
    "disappointed",
    "/ˌdɪsəˈpɔɪntɪd/",
    "decepcionado",
    "They were disappointed by the result.",
    "Eles ficaram decepcionados com o resultado.",
    "Emoções",
    VocabularyLevel.INTERMEDIATE,
  ),
  vocabulary(
    "environment",
    "/ɪnˈvaɪrənmənt/",
    "meio ambiente",
    "We should protect the environment together.",
    "Devemos proteger o meio ambiente juntos.",
    "Natureza",
    VocabularyLevel.INTERMEDIATE,
  ),
  vocabulary(
    "forecast",
    "/ˈfɔːrkæst/",
    "previsão",
    "The forecast says it may rain tonight.",
    "A previsão diz que pode chover hoje à noite.",
    "Natureza",
    VocabularyLevel.INTERMEDIATE,
  ),
  vocabulary(
    "achievement",
    "/əˈtʃiːvmənt/",
    "conquista",
    "Finishing the course was a major achievement.",
    "Concluir o curso foi uma grande conquista.",
    "Cotidiano",
    VocabularyLevel.INTERMEDIATE,
  ),

  vocabulary(
    "acknowledge",
    "/əkˈnɒlɪdʒ/",
    "reconhecer",
    "The report acknowledges the limits of the research.",
    "O relatório reconhece os limites da pesquisa.",
    "Comunicação",
    VocabularyLevel.ADVANCED,
  ),
  vocabulary(
    "compelling",
    "/kəmˈpelɪŋ/",
    "convincente",
    "She presented a compelling argument for change.",
    "Ela apresentou um argumento convincente a favor da mudança.",
    "Comunicação",
    VocabularyLevel.ADVANCED,
  ),
  vocabulary(
    "ambiguous",
    "/æmˈbɪɡjuəs/",
    "ambíguo",
    "The contract contains several ambiguous clauses.",
    "O contrato contém várias cláusulas ambíguas.",
    "Comunicação",
    VocabularyLevel.ADVANCED,
  ),
  vocabulary(
    "meticulous",
    "/məˈtɪkjələs/",
    "meticuloso",
    "His meticulous notes helped the entire team.",
    "As anotações meticulosas dele ajudaram toda a equipe.",
    "Trabalho",
    VocabularyLevel.ADVANCED,
  ),
  vocabulary(
    "entrepreneur",
    "/ˌɒntrəprəˈnɜːr/",
    "empreendedor",
    "The entrepreneur launched a sustainable company.",
    "O empreendedor lançou uma empresa sustentável.",
    "Trabalho",
    VocabularyLevel.ADVANCED,
  ),
  vocabulary(
    "feasible",
    "/ˈfiːzəbəl/",
    "viável",
    "The engineers proposed a feasible solution.",
    "Os engenheiros propuseram uma solução viável.",
    "Trabalho",
    VocabularyLevel.ADVANCED,
  ),
  vocabulary(
    "curriculum",
    "/kəˈrɪkjələm/",
    "currículo escolar",
    "The new curriculum emphasizes critical thinking.",
    "O novo currículo escolar enfatiza o pensamento crítico.",
    "Educação",
    VocabularyLevel.ADVANCED,
  ),
  vocabulary(
    "proficiency",
    "/prəˈfɪʃənsi/",
    "proficiência",
    "The role requires proficiency in two languages.",
    "A função exige proficiência em dois idiomas.",
    "Educação",
    VocabularyLevel.ADVANCED,
  ),
  vocabulary(
    "inevitable",
    "/ɪnˈevɪtəbəl/",
    "inevitável",
    "Some degree of uncertainty is inevitable.",
    "Algum grau de incerteza é inevitável.",
    "Cotidiano",
    VocabularyLevel.ADVANCED,
  ),
  vocabulary(
    "resilient",
    "/rɪˈzɪliənt/",
    "resiliente",
    "The community remained resilient after the storm.",
    "A comunidade permaneceu resiliente após a tempestade.",
    "Emoções",
    VocabularyLevel.ADVANCED,
  ),
  vocabulary(
    "overwhelmed",
    "/ˌoʊvərˈwelmd/",
    "sobrecarregado",
    "He felt overwhelmed by the amount of information.",
    "Ele se sentiu sobrecarregado com a quantidade de informação.",
    "Emoções",
    VocabularyLevel.ADVANCED,
  ),
  vocabulary(
    "biodiversity",
    "/ˌbaɪoʊdaɪˈvɜːrsəti/",
    "biodiversidade",
    "The forest supports remarkable biodiversity.",
    "A floresta sustenta uma biodiversidade notável.",
    "Natureza",
    VocabularyLevel.ADVANCED,
  ),
  vocabulary(
    "drought",
    "/draʊt/",
    "seca",
    "The prolonged drought damaged local crops.",
    "A seca prolongada prejudicou as plantações locais.",
    "Natureza",
    VocabularyLevel.ADVANCED,
  ),
  vocabulary(
    "itinerary",
    "/aɪˈtɪnəreri/",
    "itinerário",
    "Our itinerary includes three coastal towns.",
    "Nosso itinerário inclui três cidades costeiras.",
    "Viagem",
    VocabularyLevel.ADVANCED,
  ),
  vocabulary(
    "hospitality",
    "/ˌhɒspɪˈtæləti/",
    "hospitalidade",
    "We were touched by their generous hospitality.",
    "Ficamos comovidos com a generosa hospitalidade deles.",
    "Viagem",
    VocabularyLevel.ADVANCED,
  ),
  vocabulary(
    "wholesome",
    "/ˈhoʊlsəm/",
    "saudável",
    "The café serves simple, wholesome meals.",
    "O café serve refeições simples e saudáveis.",
    "Alimentação",
    VocabularyLevel.ADVANCED,
  ),
  vocabulary(
    "aftertaste",
    "/ˈæftərteɪst/",
    "sabor residual",
    "The tea has a slightly sweet aftertaste.",
    "O chá tem um sabor residual levemente doce.",
    "Alimentação",
    VocabularyLevel.ADVANCED,
  ),
  vocabulary(
    "household",
    "/ˈhaʊshoʊld/",
    "lar; domicílio",
    "Energy use fell across the entire household.",
    "O consumo de energia caiu em todo o domicílio.",
    "Casa",
    VocabularyLevel.ADVANCED,
  ),
];

export const achievementSeed = [
  {
    code: "FIRST_WORD",
    title: "Primeiro passo",
    description: "Aprenda sua primeira palavra.",
    icon: "sprout",
    requiredValue: 1,
    type: AchievementType.WORDS_LEARNED,
  },
  {
    code: "WORDS_10",
    title: "Vocabulário crescente",
    description: "Aprenda 10 palavras.",
    icon: "book-open",
    requiredValue: 10,
    type: AchievementType.WORDS_LEARNED,
  },
  {
    code: "WORDS_50",
    title: "Colecionador de palavras",
    description: "Aprenda 50 palavras.",
    icon: "library",
    requiredValue: 50,
    type: AchievementType.WORDS_LEARNED,
  },
  {
    code: "REVIEW_10",
    title: "Prática constante",
    description: "Conclua 10 revisões.",
    icon: "repeat-2",
    requiredValue: 10,
    type: AchievementType.REVIEWS_COMPLETED,
  },
  {
    code: "REVIEW_100",
    title: "Memória afiada",
    description: "Conclua 100 revisões.",
    icon: "brain",
    requiredValue: 100,
    type: AchievementType.REVIEWS_COMPLETED,
  },
  {
    code: "STREAK_3",
    title: "Pegando o ritmo",
    description: "Mantenha uma sequência de 3 dias.",
    icon: "flame",
    requiredValue: 3,
    type: AchievementType.STREAK_DAYS,
  },
  {
    code: "STREAK_30",
    title: "Imparável",
    description: "Mantenha uma sequência de 30 dias.",
    icon: "calendar-check",
    requiredValue: 30,
    type: AchievementType.STREAK_DAYS,
  },
  {
    code: "MASTER_10",
    title: "Domínio inicial",
    description: "Domine 10 palavras.",
    icon: "badge-check",
    requiredValue: 10,
    type: AchievementType.WORDS_MASTERED,
  },
  {
    code: "MASTER_50",
    title: "Mestre das palavras",
    description: "Domine 50 palavras.",
    icon: "crown",
    requiredValue: 50,
    type: AchievementType.WORDS_MASTERED,
  },
  {
    code: "XP_1000",
    title: "Mil pontos",
    description: "Acumule 1.000 pontos de experiência.",
    icon: "trophy",
    requiredValue: 1000,
    type: AchievementType.XP_EARNED,
  },
] as const;

export const dailyMissionSeed = [
  {
    code: "LEARN_3",
    title: "Três novidades",
    description: "Aprenda 3 palavras hoje.",
    xpReward: 30,
    targetValue: 3,
    type: MissionType.WORDS_LEARNED,
  },
  {
    code: "LEARN_5",
    title: "Explorador",
    description: "Aprenda 5 palavras hoje.",
    xpReward: 50,
    targetValue: 5,
    type: MissionType.WORDS_LEARNED,
  },
  {
    code: "REVIEW_5",
    title: "Revisão rápida",
    description: "Revise 5 palavras hoje.",
    xpReward: 25,
    targetValue: 5,
    type: MissionType.WORDS_REVIEWED,
  },
  {
    code: "REVIEW_10",
    title: "Sessão de memória",
    description: "Revise 10 palavras hoje.",
    xpReward: 50,
    targetValue: 10,
    type: MissionType.WORDS_REVIEWED,
  },
  {
    code: "STREAK_3",
    title: "Constância",
    description: "Alcance uma sequência de 3 dias.",
    xpReward: 40,
    targetValue: 3,
    type: MissionType.STREAK_DAYS,
  },
  {
    code: "STREAK_7",
    title: "Semana completa",
    description: "Alcance uma sequência de 7 dias.",
    xpReward: 100,
    targetValue: 7,
    type: MissionType.STREAK_DAYS,
  },
  {
    code: "MASTER_1",
    title: "Domínio do dia",
    description: "Domine 1 palavra hoje.",
    xpReward: 40,
    targetValue: 1,
    type: MissionType.WORDS_MASTERED,
  },
  {
    code: "MASTER_3",
    title: "Trio dominado",
    description: "Domine 3 palavras hoje.",
    xpReward: 90,
    targetValue: 3,
    type: MissionType.WORDS_MASTERED,
  },
] as const;
